// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHqcsMi2rRuXZP7kySIIDd7sSO0qXqh8s',
    appId: '1:577155010875:web:76756242e6f875e3ce271e',
    messagingSenderId: '577155010875',
    projectId: 'athlete-s',
    authDomain: 'athlete-s.firebaseapp.com',
    storageBucket: 'athlete-s.firebasestorage.app',
    measurementId: 'G-6M9G0PMFYH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlOFYCUtFzQOYVBGa2Zs6Dw6fUYtE9GzY',
    appId: '1:577155010875:android:cbf8c89117d23269ce271e',
    messagingSenderId: '577155010875',
    projectId: 'athlete-s',
    storageBucket: 'athlete-s.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVi72367JlmEyGciadqB3kQ0FVoJjYLvI',
    appId: '1:577155010875:ios:930997da4d0171b9ce271e',
    messagingSenderId: '577155010875',
    projectId: 'athlete-s',
    storageBucket: 'athlete-s.firebasestorage.app',
    iosBundleId: 'com.example.athlead',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVi72367JlmEyGciadqB3kQ0FVoJjYLvI',
    appId: '1:577155010875:ios:553aa01a6ec7b646ce271e',
    messagingSenderId: '577155010875',
    projectId: 'athlete-s',
    storageBucket: 'athlete-s.firebasestorage.app',
    iosBundleId: 'com.example.athiPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHqcsMi2rRuXZP7kySIIDd7sSO0qXqh8s',
    appId: '1:577155010875:web:7cddf5c45c2b8e45ce271e',
    messagingSenderId: '577155010875',
    projectId: 'athlete-s',
    authDomain: 'athlete-s.firebaseapp.com',
    storageBucket: 'athlete-s.firebasestorage.app',
    measurementId: 'G-7KMR5QVN1D',
  );
}
